library(RODBC)
library(dplyr)
library(tidyr)

# ORacle Connection
dolaprod=odbcConnect(dsn="DOLAPROD2", uid="DEMOG_GIS", pwd="SD0_G1S$$", believeNRows=FALSE )

# # Creates an index for direct distribution programs
# type_index=c("SEV_DIST", "FML", "FML_SB106")
# 
# # Read in county numbers 
# cnty=readxl::read_excel("FIPSandRegion.xls")

place=readxl::read_excel("xwalk.xlsx")%>%
  mutate(LGid=as.numeric(LGid))

# # Read in population share for weighting
popshare=readr::read_csv("daniel_muni_share.csv")%>%
  left_join(readxl::read_excel("xwalk.xlsx"), by=c("countyfips"="CountyFIPS", "placefips"="PlaceFIPS"))%>%
  mutate(LGid=as.numeric(LGid),
         id=paste0(LGid, countyfips))

# Reads in Competitive View for EIAF Grants
competitive=sqlFetch(dolaprod, "FS_GRANTS.V_COMPETITIVE_GRANT", stringsAsFactors=FALSE)

# # Reads in Formulaic View for Direct Distribution programs
# formulaic=sqlFetch(dolaprod, "DLG.V_FORMULAIC_DIST", stringsAsFactors=FALSE)
# 
# fml=sqlFetch(dolaprod, "DLG.FML_TIER1_DISTRIBUTION", stringsAsFactors=FALSE)
# 
f1=formulaic%>%
    filter(PROGRAM_TYPE %in% type_index)
write.csv(f1,"formulaic_check.csv", row.names = FALSE)
# 
# 
# # Creates the county-level Direct Distribution Estimates
formulaic_sep=formulaic%>%
  mutate(county_orig=COUNTY)%>%
  separate(COUNTY, into=c("county1","county2"), sep=",")%>% # COUNTY has comma delimited Counties for multi county places
  mutate(expand=ifelse(is.na(county2), 1, 2))%>% # I need a numeric value to expand on that tells how many rows to create on expansion
    splitstackshape::expandRows(., "expand")%>% #Expands the dataset to ahve multiple rows if the place is in multiple counties
  group_by(LG_ID, DIST_DATE)%>%
  mutate(county=stringr::str_trim(ifelse(is.na(county2), county1, ifelse(lag(county1)!=county1, county1,county2))),
         county=ifelse(is.na(county), county1, county))%>% # trickery to get a single unique county for each row relying on the order generated by the logic of the expand command
  ungroup()%>%
  filter(PROGRAM_TYPE %in% type_index, DIST_DATE >  as.POSIXlt("2008-06-30"), DIST_DATE <  as.POSIXlt("2016-04-15"))%>% # Filter that leaves only the direct distribution programs and the proper timeline
  left_join(cnty, c("county"="Name"))%>%
  mutate(id=paste0(LG_ID, Fips))%>%
  left_join(popshare)%>%
  mutate(amt=DIST_AMOUNT*share)%>%
  group_by(county)%>% # groups data by county to prepare for summing
  summarize(dd_amt=sum(amt, na.rm=TRUE)) #sums amount by county
#   

eiaf=competitive%>%
  filter(PROGRAM_TYPE=="EIAF", DATE_OF_AWARD >  as.POSIXlt("2008-06-30"), DATE_OF_AWARD <  as.POSIXlt("2017-02-02"))%>%
  group_by(COUNTY)%>%
  summarize(awd=sum(AMT_AWARDED))

write.csv(eiaf, "eiaf_data_2217.csv", row.names = FALSE)

eiaf16=competitive%>%
  filter(PROGRAM_TYPE=="EIAF", DATE_OF_AWARD >  as.POSIXlt("2015-07-01"), DATE_OF_AWARD <  as.POSIXlt("2017-02-02"))%>%
  rename(awd=AMT_AWARDED)%>%
  left_join(place, by=c("LG_ID"="LGid"))

write.csv(eiaf16, "eiaf16_data_2217.csv", row.names = FALSE)


fml=readxl::read_excel("FML_TIER1_DISTRIBUTION.xlsx")%>%
  mutate(amt=DISTRIBUTION_AMT_MUNI+DISTRIBUTION_AMT_SCHOOL)%>%
  select(year=FISCAL_YEAR,COUNTY,amt_fml=amt)%>%
  group_by(COUNTY)%>%
  summarize(amt_fml=sum(amt_fml))

sb106=readxl::read_excel("SEV_DISTRIBUTION_FML_TIER1_DISTRIBUTION_SB1061.xlsx")%>%
  mutate(amt=DISTRIBUTION_AMT_MUNI+DISTRIBUTION_AMT_SCHOOL)%>%
  select(year=FISCAL_YEAR,COUNTY,amt_sb106=amt)%>%
  group_by(COUNTY)%>%
  summarize(amt_sb106=sum(amt_sb106))

sdd=readxl::read_excel("SDD_TIER1_DISTRIBUTION.xlsx")%>%
  select(year=FISCAL_YEAR,COUNTY, amt_sdd=DISTRIBUTION_AMT_ALL)%>%
  group_by(COUNTY)%>%
  summarize(amt_sdd=sum(amt_sdd))

dd=inner_join(fml, sb106)%>%
  inner_join(sdd)%>%
  mutate(awd=amt_fml+amt_sb106+amt_sdd)


write.csv(dd, "direct_distribution_data_091517.csv", row.names = FALSE)


### Direct Distribution FY16

fml16=readxl::read_excel("FML_TIER1_DISTRIBUTION.xlsx")%>%
  mutate(amt=DISTRIBUTION_AMT_MUNI+DISTRIBUTION_AMT_SCHOOL)%>%
  select(year=FISCAL_YEAR,COUNTY,amt_fml=amt)%>%
  filter(year==2016)

sb10616=readxl::read_excel("SEV_DISTRIBUTION_FML_TIER1_DISTRIBUTION_SB1061.xlsx")%>%
  mutate(amt=DISTRIBUTION_AMT_MUNI+DISTRIBUTION_AMT_SCHOOL)%>%
  select(year=FISCAL_YEAR,COUNTY,amt_sb106=amt)%>%
  filter(year==2016)


sdd16=readxl::read_excel("SDD_TIER1_DISTRIBUTION.xlsx")%>%
  select(year=FISCAL_YEAR,COUNTY, amt_sdd=DISTRIBUTION_AMT_ALL)%>%
  filter(year==2016)


dd16=inner_join(fml16, sdd16)%>%
  mutate(awd=amt_fml+amt_sdd)


write.csv(dd16, "direct_distribution16_data_2217.csv", row.names = FALSE)
